version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: barbearia-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: barber
      POSTGRES_PASSWORD: barber123
      POSTGRES_DB: barbearia
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
